import { Company } from "./types";

export const INITIAL_COMPANIES: Company[] = [
  {
    id: "jde",
    name: "Jacobs Douwe Egberts (JDE)",
    sector: "Alimentación y Bebidas (Café)",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "jdepeets.com",
    phone: "+34 91 151 10 00",
    email: "info@jdespana.es",
    linkedin: "linkedin.com/company/jde-peet-s",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#E3000F",
    summary: "Una de las mayores tostadoras de café del mundo, operando marcas icónicas locales y globales tanto en el canal de consumo general como en hostelería (Horeca) profesional.",
    logoIconName: "coffee"
  },
  {
    id: "penguin",
    name: "Penguin Random House",
    sector: "Editorial / Publishing",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "penguinrandomhouse.com",
    phone: "+34 91 493 60 00",
    email: "info@penguinrandomhouse.com",
    linkedin: "linkedin.com/company/penguin-random-house-grupo-editorial",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#FF6B00",
    summary: "Grupo editorial líder mundial, enfocado en la publicación, promoción, distribución y venta directa e indirecta de libros en múltiples formatos físicos y digitales.",
    logoIconName: "book-open",
    note: "Asumido como 'Penguin' por posible error tipográfico 'Pennguin' en listados anteriores."
  },
  {
    id: "selecta",
    name: "Inveravante Selecta (Terraselecta)",
    sector: "Vending / Food Service",
    ecommerce: "No",
    model: "B2B",
    website: "selecta.es",
    phone: "+34 902 10 10 45",
    email: "info@selecta.es",
    linkedin: "linkedin.com/company/selecta-espana",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#E30613",
    summary: "Proveedor de servicios líderes en restauración automática (vending machines) y café premium para oficinas, aeropuertos y espacios públicos del país.",
    logoIconName: "cup-soda"
  },
  {
    id: "endado",
    name: "Recambios Endado S.L.",
    sector: "Automoción / Recambios",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "recambiosendado.com",
    phone: "+34 91 877 00 00",
    email: "info@recambiosendado.com",
    linkedin: "linkedin.com/company/recambios-endado",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#0056b3",
    summary: "Plataforma de comercio electrónico líder en España especializada en la venta directa de recambios, lubricantes y piezas originales de automoción.",
    logoIconName: "wrench"
  },
  {
    id: "elgrifo",
    name: "Bodegas El Grifo",
    sector: "Viticultura / Vinos",
    ecommerce: "Sí",
    model: "B2C",
    website: "elgrifo.com",
    phone: "+34 928 52 41 11",
    email: "info@elgrifo.com",
    linkedin: "linkedin.com/company/bodegas-el-grifo",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#D4AF37",
    summary: "La bodega más antigua de Canarias, fundada en 1775, dedicada a la producción tradicional de vinos volcánicos de excelente calidad y gran carisma histórico.",
    logoIconName: "grape"
  },
  {
    id: "kde",
    name: "Koninklijke Douwe Egberts",
    sector: "Alimentación y Bebidas",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "kde.com",
    phone: "+31 20 558 1111",
    email: "info@kde.com",
    linkedin: "linkedin.com/company/douwe-egberts",
    inSpain: true,
    flagCode: "NL",
    brandColor: "#0033A0",
    summary: "Casa matriz holandesa de JDE Coffee, custodio del patrimonio histórico de café y té de Douwe Egberts, con fuerte red de distribución en la Unión Europea.",
    logoIconName: "glass-water"
  },
  {
    id: "vaughan",
    name: "Vaughan Systems",
    sector: "Educación / EdTech",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "vaughan.es",
    phone: "+34 91 547 00 00",
    email: "info@vaughan.es",
    linkedin: "linkedin.com/company/vaughan-systems",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#CC0000",
    summary: "Principal empresa de enseñanza de inglés en España, con soluciones de cursos corporativos presenciales, e-learning masivo, contenidos de radio y editorial propia.",
    logoIconName: "graduation-cap",
    note: "El nombre original parecía fusionar entidades comerciales (Entrecanales, Domecq, Vaughan). Se priorizó Vaughan Systems."
  },
  {
    id: "parcel",
    name: "Parcel.ONE",
    sector: "Logística / Last Mile",
    ecommerce: "Sí",
    model: "B2B",
    website: "parcelone.de",
    phone: "+49 (0) 6033 9170",
    email: "info@parcelone.de",
    linkedin: "linkedin.com/company/parcel-one",
    inSpain: true,
    flagCode: "DE",
    brandColor: "#FF6600",
    summary: "Gateway de logística internacional que agrupa envíos transfronterizos para optimizar repartos de e-commerce mediante transportistas locales especializados.",
    logoIconName: "truck"
  },
  {
    id: "euronet",
    name: "Euronet Telerecarga (E-Pay)",
    sector: "Servicios Financieros / Telecom",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "euronetworldwide.com",
    phone: "+34 91 500 00 00",
    email: "info.spain@euronetworldwide.com",
    linkedin: "linkedin.com/company/euronet-worldwide",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#0055A4",
    summary: "División especializada en transferencias, recargas de saldo móvil prepago, y procesamiento seguro de transacciones en puntos de venta a nivel internacional.",
    logoIconName: "credit-card"
  },
  {
    id: "campomundo",
    name: "Campo Mundo Healthy",
    sector: "Alimentación Saludable",
    ecommerce: "Sí",
    model: "B2C",
    website: "campomundo.com",
    phone: "+34 91 000 00 00",
    email: "hola@campomundo.com",
    linkedin: "linkedin.com/company/campo-mundo",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#4CAF50",
    summary: "Marca innovadora dedicada al desarrollo y distribución de alimentos ecológicos, funcionales y saludables que promueven un estilo de vida consciente y equilibrado.",
    logoIconName: "heart"
  },
  {
    id: "sgel",
    name: "SGEL S.A.",
    sector: "Educación / Editorial",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "sgel.es",
    phone: "+34 91 745 18 00",
    email: "sgel@sgel.es",
    linkedin: "linkedin.com/company/sgel",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#004B87",
    summary: "Sociedad General Española de Librería, líder en distribución de prensa, revistas y didáctica editorial para la enseñanza de idiomas extranjeros (ELE).",
    logoIconName: "languages"
  },
  {
    id: "regalador",
    name: "Honest and Smart (Regalador)",
    sector: "Regalos Corporativos / E-commerce",
    ecommerce: "Sí",
    model: "B2B y B2C",
    website: "regalador.com",
    phone: "+34 91 000 00 00",
    email: "hola@regalador.com",
    linkedin: "linkedin.com/company/regalador",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#6A0DAD",
    summary: "Plataforma de e-commerce emocional especializada en regalos creativos, personalizados y regalos de agradecimiento corporativo listos para enviar.",
    logoIconName: "gift"
  },
  {
    id: "micenas",
    name: "Corporación Micenas (Feroz)",
    sector: "Facility Management / Limpieza",
    ecommerce: "No",
    model: "B2B",
    website: "corporacionmicenas.com",
    phone: "+34 91 640 00 00",
    email: "info@corporacionmicenas.com",
    linkedin: "linkedin.com/company/corporacion-micenas",
    inSpain: true,
    flagCode: "ES",
    brandColor: "#002147",
    summary: "Grupo multiservicios dedicado al mantenimiento preventivo, limpieza técnica interna, desinfección integral y externalización hotelera o corporativa.",
    logoIconName: "building"
  }
];
